services:
    APISkeletons\Doctrine\GraphQL\Command\ConfigurationSkeletonCommand:
        arguments: []
        tags:
            - { name: 'console.command', command: 'graphql:config-skeleton' } 
        
